# Generated by Django 3.2.5 on 2021-07-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date/Time')),
                ('local', models.CharField(choices=[('munchen', 'Munschen'), ('wurzburg', 'Wurzburg'), ('berlin', 'Berlin')], max_length=50, verbose_name='Local')),
                ('mode', models.IntegerField(choices=[(1, 'One-Match'), (3, 'Best of 3'), (5, 'Best of 5')], verbose_name='Game mode')),
                ('team1', models.ManyToManyField(related_name='meetings_team1', to='players.Player')),
                ('team2', models.ManyToManyField(related_name='meetings_team2', to='players.Player')),
            ],
        ),
    ]
