# Generated by Django 3.2.5 on 2021-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date/Time'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='local',
            field=models.CharField(choices=[('munchen', 'Munschen'), ('wurzburg', 'Wurzburg'), ('berlin', 'Berlin')], max_length=50, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='mode',
            field=models.IntegerField(choices=[(1, 'One-Match'), (3, 'Best of 3'), (5, 'Best of 5')], verbose_name='Game mode'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='team1',
        ),
        migrations.AddField(
            model_name='meeting',
            name='team1',
            field=models.ManyToManyField(related_name='meetings_team1', to='players.Player'),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='team2',
        ),
        migrations.AddField(
            model_name='meeting',
            name='team2',
            field=models.ManyToManyField(related_name='meetings_team2', to='players.Player'),
        ),
    ]
