# Generated by Django 3.2.5 on 2021-07-07 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_team1', models.CharField(max_length=200, verbose_name='Position of Team 1')),
                ('result', models.CharField(max_length=200, verbose_name='Result')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='meetings.meeting')),
            ],
        ),
    ]
