# Generated by Django 3.2.5 on 2021-07-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=200, unique=True, verbose_name="Player's last name")),
                ('office', models.CharField(choices=[('munchen', 'Munschen'), ('wurzburg', 'Wurzburg'), ('berlin', 'Berlin')], max_length=50, verbose_name='Office')),
            ],
        ),
    ]
